name: HACS

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hacs_repo:
    runs-on: "ubuntu-latest"
    name: HACS Repo Validation
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
